import { AppShell } from '@/components/shell/AppShell';
import { NotYetBuilt } from '@/components/shell/NotYetBuilt';

export default function CoordinatorTasksPage() {
  return (
    <AppShell breadcrumbs={['Coordinator', 'Tasks']}>
      <div className="page-head">
        <div>
          <span className="eyebrow">Coordinator · Tasks</span>
          <h1>Workup &amp; <span className="emph">follow-ups</span>.</h1>
        </div>
      </div>

      <NotYetBuilt
        title="Per-case workup checklist"
        milestone="Phase 2 · M9"
        description="Tasks generated by IntakeOrchestrator + ReadinessAgent (labs, EKG, consults, education) — coordinator triages, marks complete, escalates. Backed by `tasks` table once M9 lands."
      />
    </AppShell>
  );
}
