'use client';

import { useState } from 'react';
import { AppShell } from '@/components/shell/AppShell';

interface Task {
  lbl: string;
  sub: string;
  assignee: 'PO' | 'RV' | 'DL';
  due: string;
  ai: boolean;
  overdue: boolean;
  done: boolean;
}

const INITIAL: Task[] = [
  { lbl: 'Chase Dr. Lin (cardio) for Daniel Shaw consult response', sub: '3rd follow-up · ReferralAgent auto-escalated',         assignee: 'PO', due: 'Today · 2pm',  ai: true,  overdue: false, done: false },
  { lbl: 'Review SMS nudge for Maya Khan',                          sub: 'PatientCommsAgent draft — reading level 6, 142 chars',  assignee: 'PO', due: 'Today · 4pm',  ai: true,  overdue: false, done: false },
  { lbl: 'Call Nora Bright for labs handoff from Outside Lab',      sub: 'DocumentationAgent portal scrape failed 2x',            assignee: 'PO', due: 'Today · 5pm',  ai: false, overdue: false, done: false },
  { lbl: 'Submit prior auth for Jordan Park TKA',                   sub: 'TaskTrackerAgent drafted · awaiting human sign-off',    assignee: 'RV', due: 'Tomorrow',     ai: true,  overdue: false, done: false },
  { lbl: 'Confirm OR-3 slot with Ella Guo',                         sub: 'TaskTrackerAgent held 10am May 6',                      assignee: 'PO', due: 'Tomorrow',     ai: true,  overdue: false, done: false },
  { lbl: 'Send education pack to Alex Rivera',                      sub: 'PatientCommsAgent drafted · pre-op prep, 3 cards',      assignee: 'RV', due: 'Yesterday',    ai: true,  overdue: true,  done: false },
  { lbl: 'Book transport for Raj Patel · day-of',                   sub: 'PreHabAgent flagged — no ride on file',                 assignee: 'PO', due: 'Apr 24',       ai: true,  overdue: true,  done: false },
  { lbl: 'Fax records to Bayview ENT for Daniel Shaw',              sub: 'Manual task · no agent route',                          assignee: 'PO', due: 'Apr 22',       ai: false, overdue: true,  done: false },
  { lbl: 'Update insurance eligibility for Tomás Valle',            sub: 'TaskTrackerAgent flagged expired card',                 assignee: 'RV', due: 'May 01',       ai: true,  overdue: false, done: false },
  { lbl: 'Post-op follow-up call · Kai Nielsen',                    sub: 'Day 2 check-in · patient reports mild pain',            assignee: 'PO', due: 'Today',        ai: false, overdue: false, done: false },
  { lbl: 'Approve SMS — NPO reminder batch (11 patients)',          sub: 'PatientCommsAgent drafted — sends 10pm tonight',        assignee: 'PO', due: 'Today · 6pm',  ai: true,  overdue: false, done: false },
  { lbl: 'Confirm anesthesia clearance received · Lena Rossi',      sub: 'Dr. Chen signed 9:42a',                                 assignee: 'PO', due: '—',            ai: false, overdue: false, done: true },
];

const AS_NAMES: Record<Task['assignee'], string> = { PO: 'Priya O.', RV: 'Rico V.', DL: 'Dana L.' };

const FILTERS = ['Open · 42', 'AI-drafted · 12', 'Overdue · 5', 'Done'];

export default function CoordinatorTasksPage() {
  const [tasks, setTasks] = useState<Task[]>(INITIAL);

  const toggle = (i: number) => setTasks((arr) => arr.map((t, j) => (j === i ? { ...t, done: !t.done } : t)));

  return (
    <AppShell breadcrumbs={['Coordinator', 'Tasks']}>
      <div className="page-head">
        <div>
          <span className="eyebrow">Coordinator · Tasks</span>
          <h1>
            Your <span className="emph"><em>queue</em></span>.
          </h1>
        </div>
        <div className="page-actions">
          <button className="btn btn-outline-dark">Filter</button>
          <button className="btn btn-primary">New task</button>
        </div>
      </div>

      <div className="toolbar">
        <div className="seg">
          {FILTERS.map((f, i) => (
            <button key={f} type="button" className={i === 0 ? 'active' : undefined}>
              {f}
            </button>
          ))}
        </div>
        <div className="spacer" />
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: '0.75rem', color: 'var(--ink-500)' }}>
          Sort · due date
        </span>
      </div>

      <div className="ai-banner">
        <b>◆ AI-drafted tasks</b> auto-generated by agents when cases enter a new phase. You review,
        assign, and sign off — agents don&apos;t act unilaterally.
      </div>

      <div className="task-list">
        {tasks.map((t, i) => (
          <div className={`r${t.done ? ' done' : ''}`} key={i}>
            <div className="cb" onClick={() => toggle(i)} style={{ cursor: 'pointer' }} />
            <div className="lbl">
              {t.lbl}
              {t.ai && <span className="ai" style={{ marginLeft: '0.375rem' }}>◆ AI-drafted</span>}
              <div className="s">{t.sub}</div>
            </div>
            <div className="as">
              <span className="av">{t.assignee}</span>
              {AS_NAMES[t.assignee]}
            </div>
            <div className={`due${t.overdue ? ' overdue' : ''}`}>{t.due}</div>
            <div>
              <span className={`status-pill ${t.done ? 'cleared' : t.overdue ? 'deferred' : 'pending'}`}>
                {t.done ? 'done' : t.overdue ? 'overdue' : 'open'}
              </span>
            </div>
          </div>
        ))}
      </div>
    </AppShell>
  );
}
