import { index, pgTable, text, timestamp, uuid, varchar } from 'drizzle-orm/pg-core';
import { baseColumns, taskAssigneeRoleEnum, taskStatusEnum } from './base';
import { cases } from './cases';
import { facilities } from './facilities';
import { users } from './users';

/**
 * Task — a single actionable workup item attached to a case.
 *
 * Examples: "Order pre-op labs", "Schedule cardiology consult",
 * "Patient signs informed consent", "Anesthesia clearance review".
 *
 * `assigneeRole` is required (so the right shell can list it); the
 * specific user (`assigneeUserId`) is optional and narrows further.
 *
 * In M9 these get auto-generated by IntakeOrchestrator when a case
 * is created and updated by ReadinessAgent / RiskScreening as their
 * checks run; for now coordinators create them manually.
 */
export const tasks = pgTable(
  'tasks',
  {
    ...baseColumns,
    facilityId: uuid('facility_id')
      .notNull()
      .references(() => facilities.id),
    caseId: uuid('case_id')
      .notNull()
      .references(() => cases.id, { onDelete: 'cascade' }),
    title: varchar('title', { length: 256 }).notNull(),
    description: text('description'),
    status: taskStatusEnum('status').notNull().default('pending'),
    assigneeRole: taskAssigneeRoleEnum('assignee_role').notNull(),
    assigneeUserId: uuid('assignee_user_id').references(() => users.id),
    dueDate: timestamp('due_date', { withTimezone: true, mode: 'date' }),
    completedAt: timestamp('completed_at', { withTimezone: true, mode: 'date' }),
    completedBy: uuid('completed_by').references(() => users.id),
  },
  (table) => [
    index('tasks_case_idx').on(table.caseId),
    index('tasks_facility_idx').on(table.facilityId),
    index('tasks_assignee_user_idx').on(table.assigneeUserId),
    index('tasks_assignee_role_status_idx').on(table.assigneeRole, table.status),
  ],
);

export type Task = typeof tasks.$inferSelect;
export type NewTask = typeof tasks.$inferInsert;
